# Generated by Django 3.2.9 on 2022-01-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_new_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
